export default Object.freeze({
    SNS_ORDER_READY_ARN: process.env.SNS_ORDER_READY_ARN ?? 'SNS_ORDER_READY_ARN',
    SNS_INGREDIENTS_NEEDED_ARN: process.env.SNS_INGREDIENTS_NEEDED_ARN ?? 'SNS_INGREDIENTS_NEEDED_ARN',
    SNS_INGREDIENTS_PURCHASED_ARN: process.env.SNS_INGREDIENTS_PURCHASED_ARN ?? 'SNS_INGREDIENTS_PURCHASED_ARN',
    SNS_INVENTORY_READY_ARN: process.env.SNS_INVENTORY_READY_ARN ?? 'SNS_INVENTORY_READY_ARN',
    SNS_INVENTORY_SHORTAGE_ARN: process.env.SNS_INVENTORY_SHORTAGE_ARN ?? 'SNS_INVENTORY_SHORTAGE_ARN',
});
